### ISSUE TITLE
Mobile Menu stuck when scrolling too fast.

### ISSUE THREAD

**Issue by denzelchia** [presscustomizr/customizr#352]
In iPhone Safari browser, I am using iPhone 6.
I set the menu with a lot of items until it overflows the view port height.
26 menu items, which includes sub menu item.

I am able to scroll down to the end of the menu, if I do it normally.
It gets stuck if I scroll it too quickly. 
If I scroll it too quickly, up and down, only the webpage behind it scrolls, not the menu.

Hope this information helps.

Thanks!
Denzel

**Comment by eri-trabiccolo** [comment]
Hello Denzel,
thanks for reporting this, which menu?
Vertical or the horizontal?

**Comment by denzelchia** [comment]
Hi Rocco,

It horizontal menu. No side menu.
Sorry forgotten to mention this.

Thanks!
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks,
horizontal menu, with " For mobile devices (responsive), limit the height of the dropdown menu block to the visible viewport." unchecked then?

**Comment by denzelchia** [comment]
Hi Rocco,

Sorry. I am not sure.
Get back to you later tonight.
I am not at home now. :)

Sorry for causing inconvenience. 

Thanks!

**Comment by eri-trabiccolo** [comment]
No problem Denzel :),
I will try to reproduce it with my smartphone.

Have a great .. day(?)

**Comment by denzelchia** [comment]
Hi Rocco,

I have  Horizontal Menu with "For mobile devices (responsive), limit the height of the dropdown menu block to the visible viewport." checked.

Screenshot - http://i.imgur.com/ge4vRAP.jpg

Thanks!
Denzel

**Comment by eri-trabiccolo** [comment]
Thanks Denzel,
and yes makes sense, which it happens just with that option enabled. The thing is that in that case while scrolling "over" the menu you scroll the menu till the menu ends then you start to scroll the page. Maybe doing this scroll "at high speed" cause that issue with safari, mah.
Cannot reproduce it though with my LG 4XHD, I have to further investigate on it.
Not sure we can really do something, except making the menu modal.
Can you please test this when you can?
Temporary add the following the your custom-css.

@media (max-width: 979px){ #tc-page-wrap { position: fixed; width:100%;} }

And try if it still occurs.
Don't care about the fact that the page is fixed, it's just to understand if we have to fix it when the menu is open. :)

Thank you Denzel!

**Comment by denzelchia** [comment]
Hi Rocco,
Tried the CSS.
Yes, the menu scrolling works properly if the page is fixed.
Thanks!

**Comment by eri-trabiccolo** [comment]
Thanks @denzelchia 
So @Nikeo what do you think? Do we want to make the mobile menu when limited to the viewport modal?

**Comment by Nikeo** [comment]
I still don't really understand why / when this problem will occur : long menu ok but it's not clear on which devices are impacted. apple only?

Let's wait and see if it's a recurrent bug report.

**Comment by eri-trabiccolo** [comment]
Ok. ;)
It can also be that it happens because a "pan" is detected.
Maybe we can consider a new option when dropdown limit is on => make it modal
we'll see.
